// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/4/2025, 4:41:15 PM
const configMerger = require("/Users/madebyporter/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/plugins/**/*.{js,ts,mjs}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/composables/**/*.{js,ts,mjs}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/utils/**/*.{js,ts,mjs}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/madebyporter/Library/CloudStorage/Dropbox/MBP/Products/roastgpt/app.config.{js,ts,mjs}"] } }));

module.exports = config
